/* Script création base de donnée et seeding oKanban */
-- On démarre une transaction afin de s'assurer de la cohénce globale de la BDD
BEGIN;

-- On supprime les tables si elles existent
DROP TABLE IF EXISTS "list",
"card",
"tag",
"card_has_tag";

-- Ensuite on la (re)crée
CREATE TABLE "list" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL DEFAULT '',
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "card" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" TEXT NOT NULL DEFAULT '',
  "color" TEXT NOT NULL DEFAULT '#FFF',
  "position" INTEGER NOT NULL DEFAULT 0,
  -- ON DELETE CASCADE pour supprimer les cartes affectés à une liste lors de la suppression de celle-ci
  "list_id" INTEGER NOT NULL REFERENCES list("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL DEFAULT '',
  "color" TEXT NOT NULL DEFAULT '#FFF',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "card_has_tag" (
  -- "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "card_id" INTEGER NOT NULL REFERENCES card("id") ON DELETE CASCADE,
  "tag_id" INTEGER NOT NULL REFERENCES tag("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- SEEDING 
INSERT INTO
  "tag" ("id", "name", "color")
VALUES
  (1, 'Urgent', '#0000FF');

INSERT INTO
  "list" ("id", "name", "position")
VALUES
  (1, 'To Do', 1),
  (2, 'Done', 2);

INSERT INTO
  "card" ("id", "content", "position", "color", "list_id")
VALUES
  (1, 'Do the dishes', 1, '#0000FF', 1),
  (2, 'Mop the floor', 1, '#0000FF', 2),
  (3, 'Destroy all humans', 2, '#FF0000', 1);

INSERT INTO
  "card_has_tag" ("card_id", "tag_id")
VALUES
  (3, 1);

COMMIT;